# Generated by Django 4.1.6 on 2023-02-15 18:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0005_website'),
    ]

    operations = [
        migrations.AddField(
            model_name='website',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
    ]
