# Generated by Django 4.1.6 on 2023-02-24 12:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0015_shop_description'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Shop',
        ),
    ]
