# Generated by Django 4.1.6 on 2023-02-24 13:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0017_shop'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='luxury',
            field=models.BooleanField(default=False, null=True),
        ),
    ]
