# Generated by Django 4.1.6 on 2023-02-26 12:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0018_product_luxury'),
    ]

    operations = [
        migrations.AddField(
            model_name='shop',
            name='luxury',
            field=models.BooleanField(default=False, null=True),
        ),
    ]
