# Generated by Django 4.1.6 on 2023-02-26 13:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0019_shop_luxury'),
    ]

    operations = [
        migrations.AddField(
            model_name='shop',
            name='luxury_1',
            field=models.BooleanField(default=False, null=True),
        ),
    ]
