# Generated by Django 4.1.6 on 2023-02-26 13:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0020_shop_luxury_1'),
    ]

    operations = [
        migrations.AddField(
            model_name='shop',
            name='luxury_2',
            field=models.BooleanField(default=False, null=True),
        ),
    ]
