# Generated by Django 4.0.2 on 2023-02-20 08:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('category', '0002_categoryshippingaddress_categoryorderitem'),
    ]

    operations = [
        migrations.AddField(
            model_name='categoryproduct',
            name='discount_price',
            field=models.DecimalField(decimal_places=2, default=1, max_digits=7),
            preserve_default=False,
        ),
    ]
