# Generated by Django 4.1.6 on 2023-02-14 17:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_admin_text_admin_title_admin_writer'),
    ]

    operations = [
        migrations.AddField(
            model_name='admin',
            name='image',
            field=models.ImageField(default=1, upload_to='static/images'),
            preserve_default=False,
        ),
    ]
